
name: Update Nightly Jar

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:

  update:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Check branch
      if: ${{ github.ref != 'refs/heads/master' }}
      run: |
        echo "This workflow is only allowed to run from the master branch"
        exit 1

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0

    - name: Build with Gradle
      run: ./gradlew shadowJar

    - name: Update nightly tag
      run: |

        git tag -f nightly '${{ github.sha }}'
        git push -f origin refs/tags/nightly:refs/tags/nightly

        remote_tag_updated=''
        for i in {1..5}; do
          remote_tag_sha=$(git ls-remote --tags origin refs/tags/nightly | awk '{print $1}')
          if [[ "${remote_tag_sha}" == '${{ github.sha }}' ]]; then
            remote_tag_updated=1
            break
          fi
          echo "[${i}/5] Remote tag not updated yet, sleeping for 2 seconds ..."
          sleep 2
        done

        if [[ ! "${remote_tag_updated}" ]]; then
          echo 'GitHub timed out updating the remote tag'
          exit 1
        fi

    - name: Prepare release body
      run: |
        git show -s --format=%B '${{ github.sha }}' > release_body.txt

    - name: Create release
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      with:
        name: Nightly
        prerelease: true
        tag_name: nightly
        body_path: release_body.txt
        files: build/libs/InfinityAreas.jar
